### PR TITLE
Update tag name for StackOverflow

### PR DESCRIPTION
**Pull request by StephenKing**
The usage guidance of the [jenkins-workflow](http://stackoverflow.com/questions/tagged/jenkins-workflow) tag on StackOverflow recommends using tag [jenkins-pipeline](http://stackoverflow.com/questions/tagged/jenkins-pipeline) instead.

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
👍

**Comment by jglick** [comment]
Ah, so you are the one who made that edit to the excerpt. It was supposed to be an alias, not a separate tag. I suppose you missed [this](http://meta.stackoverflow.com/q/315048/12916).

**Comment by StephenKing** [comment]
Hey @jglick, I followed up to your [posting on meta](http://meta.stackoverflow.com/questions/315048/tag-rename-request-jenkins-workflow-%E2%86%92-jenkins-pipeline/335402#335402).

**Comment by StephenKing** [comment]
@jglick do you agree with my suggestion on the meta site? Do you have any concerns to merge this PR?

**Comment by StephenKing** [comment]
ping @jglick

**Pull request merged**
