### PR TITLE
[JENKINS-35247] Delegate to Git and Subversion plugins via reflection (1.14.x)

### PR DESCRIPTION
**Pull request by jglick**
Preparing a new baseline for https://github.com/jenkinsci/git-plugin/pull/406 that should avoid a cyclic dependency error.

@reviewbybees

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Looks good to me 🐝 
All this code has a limited lifetime till new SVN/Git plugins get released, right?

**Comment by rsandell** [comment]
:bee:

**Comment by recena** [comment]
@oleg-nenashev I hope to cut a release of **Subversion Plugin** as soon as I review the PR https://github.com/jenkinsci/subversion-plugin/pull/161

**Comment by jglick** [comment]
> All this code has a limited lifetime till new SVN/Git plugins get released, right?

Well, the 1.4.x and 1.14.x branches I would probably leave as is. For trunk, https://github.com/jenkinsci/workflow-scm-step-plugin/pull/2 does the final cleanup.

**Pull request merged**
